@startuml

start

note: distances and durations are set

:create ""**resultChannel**"";

:initialize ""**pheromones**"", ""**bestResult**"" and ""**Ant**"" swarm as ""[Ants]**swarm**"";

while (""Iterations"" of iterations run?) is (no)
    fork
        :""**go** swarm[0].FindFood()"";
        detach
    fork again
        :""**go** swarm[1].FindFood()"";
        detach
    fork again
        -[hidden]->
        :...;
        detach
    fork again
        :""**go** swarm[Ants-1].FindFood()"";
        detach
    end fork

    while (received results from all ants?) is (no)
        :receive ""**result**"" over ""**resultChannel**"" and save it;

        if (""**result**"" better than ""**bestResult**"") then (true)
            :overwrite ""**bestResult**"" with ""**result**"";
        else (false)
        endif
    endwhile (yes)
    :evaporate ""**pheromones**"";
    fork
        :intensify ""**pheromones**"" along first ""**result**"";
    fork again
        :intensify ""**pheromones**"" along second ""**result**"";
    fork again
        -[hidden]->
        :...;
        detach
    fork again
        :intensify ""**pheromones**"" along last ""**result**"";
    end fork
endwhile (yes)

:update ""**trip**"" with ""**bestResult**"" data: arrival/departure times, trip end time, total distance, start/end place if not set;

:set ""**trip**"" ""steps []*Step"" and ""path []int"" from ""**bestResult**"";

@enduml